### NumPy Tutorial for CS224D
##### Thiago Akio Nakamura

Starting with a classic `quicksort` algorithm as an initial example.

In [1]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) / 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print quicksort([3, 4, 6, 11, -2, 3, 0, 2, 4, 10, 8, -2])

[-2, -2, 0, 2, 3, 3, 4, 4, 6, 8, 10, 11]


#### Basic data types:
* Numbers:

x=3
print type(x)  # Prints "<type 'int'>"
print x        # Prints "3"
print x+1      # Addition; prints"4"
print x-1      # Subtraction; prints"2"
print x*2      # Multiplication; prints"6"
print x**2     # Exponentiation; prints"9"
x += 1
print x        # Prints "4"
x *= 2
print x        # Prints "8"
y = 2.5
print type(y)  # Prints "<type 'float'>"
print y, y + 1, y * 2, y ** 2 # Prints "2.5 3.5 5.0 6.25"

* Booleans:

In [7]:
t = True
f = False
print type(t) # Prints "<type 'bool'>" 
print t and f # Logical AND; prints "False" 
print t or f  # LogicalOR; prints "True" 
print not t   # LogicalNOT; prints "False" 
print t != f  # LogicalXOR; prints "True"

<type 'bool'>
False
True
False
True


* Strings:

In [13]:
hello = 'hello'  # String literals can use single quotes 
world = "world"  # or double quotes; it does not matter.
print hello      # Prints "hello"
print len(hello) # String length; prints "5" 
hw = hello + ' ' + world # String concatenation
print hw # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12) # sprintf style string format 
print hw12 # prints "hello world 12"
  
s = "hello"
print s.capitalize() # Capitalize a string; prints "Hello"
print s.upper()      # Convert a string to uppercase; prints "HELLO"
print s.rjust(7)     # Right-justify a string, padding with spaces on the left;
print s.center(7)    # Center a string, padding with spaces;
print s.replace('l', '(ell)')
print '  world'.strip()

hello
5
hello world
hello world 12
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


### Containers
##### Lists

In [14]:
xs = [3, 1, 2]  # Create a list
print xs, xs[2] # Prints "[3, 1, 2] 2"
print xs[-1]  # Negative indices count from the end of the list;
xs[2] = 'foo' # Lists can contain elements of different types
print xs      # Prints "[3, 1, 'foo']"
xs.append('bar') # Add a new element to the end of the list
print xs
x = xs.pop() # Remove and return the lat element of the list
print x, xs

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


* Slicing:

In [16]:
nums = range(5) # range is a built-in function that creates a list
print nums      # Prints "[0, 1, 2, 3, 4]"
print nums[2:4] # Get a slice from index 2 to 4 (exclusive);
print nums[2:]  # Get a slice from index 2 to the end;
print nums[:2]  # Get a slice from the start to index 2 (exclusive)
print nums[:]   # Get a slice of the whole list;
print nums[:-1] # Slice indices can be negative;
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print nums         # Prints "[0, 1, 8, 8, 4]

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


* Loops:

In [17]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print animal
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


In [18]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

#1: cat
#2: dog
#3: monkey


* List comprehension:

In [19]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print squares # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


The code above can be replaced by:

In [21]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]
print squares # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


Comprehension can also have conditionals:

In [22]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print even_squares # Prints "[0, 4, 16]"

[0, 4, 16]


##### Dictionaries

In [25]:
d = {'cat': 'cute', 'dog': 'furry'} # Create a new dictionary
print d['cat']    # Get an entry from a dictionary; prints "cute"
print 'cat' in d  # Check if a dictionary has a given key; prints True
d['fish'] = 'wet' # Set an entry in a dictionary
print d['fish']   # Prints "wet"
# print d['monkey'] # KeyError: 'monkey' not a key of dictionary
print d.get('monkey', 'N/A') # Get an element with a default
print d.get('fish', 'N/A')   # Get an element with a default
del d['fish']     # Remoce an element from the dictionary
print d.get('fish', 'N/A') # "fish" is no longer a key

cute
True
wet
N/A
wet
N/A


* Loops:

In [26]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print 'A %s has %d legs' % (animal, legs)
# Prints "A person has 2 legs", "A spider has 8 legs", "A cat has 4 legs" on each line

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


In [27]:
d = {'person': 2, 'cat': 4, 'spider': 8} 
for animal, legs in d.iteritems():
    print 'A %s has %d legs' % (animal, legs)
# Prints "A person has 2 legs", "A spider has 8 legs", "A cat has 4 legs".

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


* Dictionary comprehensions:

In [28]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print even_num_to_square # Prints" {0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


#### Sets
A set is an unordered collection of distinct elements.

In [31]:
animals = {'cat', 'dog'}
print'cat'in animals  # Check if a nelement is in a set; prints "True"
print'fish'in animals # Prints False
animals.add('fish')   # Adds element to a set
print'fish'in animals # Prints True
print len(animals)    # Number of elements in a set
animals.add('cat')    # Add an element that is already in the set
print len(animals)    # Prints 3 again
animals.remove('cat') # Remove an element from the set
print len(animals)

True
False
True
3
3
2


* Loops:

Set are unordered, so we can't make assumptions about the order in which we visit the elements in the set.

In [35]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: dog
#3: cat


* Set comprehension:

In [36]:
from math import sqrt

nums = {int(sqrt(x)) for x in range(30)} 
print nums # Prints "set([0, 1, 2, 3, 4, 5])"

set([0, 1, 2, 3, 4, 5])


#### Tuples
A tuple is an immutable ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot.

In [43]:
d = {(x, x + 1): x for x in range(10)} # Create a dictionary
t = (5, 6)      # Create a tuple
print type(t)   # Prints <type 'tuple'>
print d[t]      # Prints 5
print d[(1, 2)] # Prints 1

<type 'tuple'>
5
1


### Functions
Python functions are defined using the `def` keyword:

In [45]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print sign(x)
# Prints "negative, "zero" and "positive"

negative
zero
positive


Function can be defines to take optional keyword arguments:

In [55]:
def hello(name, loud=False):
    if loud:
        print 'HELLO, %s!' % name.upper()
    else:
        print 'Hello, %s' % name

        
hello('Bob')
hello('Fred', loud=True)            

Hello, Bob
HELLO, FRED!


## Classes

In [56]:
class Greeter:
    
    # Constructor
    def __init__(self, name):
        self.name = name # Create an instance variable
        
    # Instance method
    def greet(self, loud=False):
        if loud:
            print 'HELLO, %s!' % self.name.upper() 
        else:
            print 'Hello, %s' % self.name
            
g = Greeter('Fred') # Construct an instance of the Greeter class
g.greet()           # Call an instance method; prints "Hello, Fred" 
g.greet(loud=True)  # Callaninstancemethod; prints"HELLO,FRED

Hello, Fred
HELLO, FRED!


## NumPy
NumPy is the core library for scientific computing in Python. It provides a high performance multidimensional array object, and tools for working with these arrays.

#### Arrays
A NumPy array is a grid of values, all of the same type, and is indexed by a tuple of non-negative integers. The number of dimensions is the `rank` of the array, he `shape` of an array is a tuple of integers giving the size of the array along each dimension.

In [58]:
import numpy as np

a = np.array([1,2,3])  # Create a rank 1 array
print type(a)          # Prints "<type 'numpy.ndarray'>"
print a.shape          # Prints "(3,)"
print a[0], a[1], a[2] # Prints "1 2 3"
a[0] = 5               # Change an element of the array 
print a                # Prints "[5, 2, 3]"
   
b = np.array([[1, 2, 3], [4, 5, 6]]) # Create a rank 2 array
print b.shape
print b[0, 0], b[0, 1], b[1, 0]      # Prints "1 2 4"

<type 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


We can create arrays in several ways:

In [60]:
a = np.zeros((2, 2))  # Create an array of all zeros
print a               # Prints "[[ 0. 0.]
                      #          [ 0. 0.]]"
b = np.ones((1, 2))   # Create an array of all ones
print b               # Prints "[[ 1. 1.]]"

c = np.full((2, 2), 7) # Create a constant array
print c                # Prints "[[7. 7.] 
                       #          [7. 7.]]"
d = np.eye(2)          # Create a 2x2 identity matrix
print d                # Prints "[[1. 0.]
                       #          [ 0. 1.]]"

e = np.random.random((2, 2)) # Create an array filled with random values
print e 

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.69646679  0.45902994]
 [ 0.39552791  0.16611179]]
