# Python and NumPy Tutorial for CS224D
#### Thiago Akio Nakamura

This is a short Python Tutorial, convering its main types and commands. Furthermore, some basic functionalities of the libraries `NumPy`, `SciPy` and `Matplotlib` are also covered. This is practically a reproduction of [this Python tutorial](http://cs231n.github.io/python-numpy-tutorial/).

## Python

Python is a widely used general-purpose, high-level programming language. Its design philosophy emphasizes code readability, and its syntax allows programmers to express concepts in fewer lines of code than would be possible in languages such as C++ or Java. The language provides constructs intended to enable clear programs on both a small and large scale.

Let's start with a classic `quicksort` algorithm as an initial example, simply to demonstrate how the Python syntax works. Note the identation is used for changing the "block" of the code.

In [1]:
# Define a function called quicksort.
def quicksort(arr):
    # Indentation change initialize the function block.
    if len(arr) <= 1:
        # Another indentation increase initialises the if statement block.
        return arr
    # Decrease in identation finishes a block and return to the previous.
    pivot = arr[len(arr) / 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

# Put any numer you want in the array you want to sort.
print quicksort([3, 4, 6, 11, -2, 3, 0, 2, 4, 10, 8, -2])

[-2, -2, 0, 2, 3, 3, 4, 4, 6, 8, 10, 11]


### Basic data types:
Let's begin with pythons basic types. The four main basic types are `integers`, `floats`, `booleans` and `strings`.
* Numbers:

In [4]:
x = 3          # Creates an integer
print type(x)  # Prints "<type 'int'>"
print x        # Prints "3"
print x + 1    # Addition; prints"4"
print x - 1    # Subtraction; prints"2"
print x * 2    # Multiplication; prints"6"
print x ** 2   # Exponentiation; prints"9"
x += 1         # Increment 'x' in 1.
print x        # Prints "4"
x *= 2         # Multiply x by 2 and assign back to itself.
print x        # Prints "8"
y = 2.5        # Creates a float.
print type(y)  # Prints "<type 'float'>"
print y, y + 1, y * 2, y ** 2 # Prints "2.5 3.5 5.0 6.25"

<type 'int'>
3
4
2
6
9
4
8
<type 'float'>
2.5 3.5 5.0 6.25


* Booleans:

In [5]:
t = True      # Creates a boolean variable with 'True' value
f = False     # Creates a boolean variable with 'False' value
print type(t) # Prints "<type 'bool'>" 
print t and f # Logical AND; prints "False" 
print t or f  # LogicalOR; prints "True" 
print not t   # LogicalNOT; prints "False" 
print t != f  # LogicalXOR; prints "True"

<type 'bool'>
False
True
False
True


* Strings:

In [8]:
hello = 'hello'  # String literals can use single quotes 
world = "world"  # or double quotes; it does not matter.
print hello      # Prints "hello"
print len(hello) # String length; prints "5" 
hw = hello + ' ' + world # String concatenation
print hw         # prints "hello world"
hw12 = '%s %s %d' % (hello, world, 12) # sprintf style string format 
print hw12       # prints "hello world 12"
  
s = "hello"
print s.capitalize() # Capitalize a string; prints "Hello"
print s.upper()      # Convert a string to uppercase; prints "HELLO"
print s.rjust(7)     # Right-justify a string, padding with spaces on the left;
print s.center(7)    # Center a string, padding with spaces;
print s.replace('l', '(ell)') # Replaces the all occurrences of 'l' by '(ell)' in the 's' string.
print '  world  '.strip() # Remove all leading and trailing space of a string.

hello
5
hello world
hello world 12
Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


### Containers
Python includes several container types as lists, dictionaries, sets and tuples.

#### Lists
It is equivalent to an array, but is resizable and can contain elements of different types.

In [9]:
xs = [3, 1, 2]   # Create a list
print xs, xs[2]  # Prints "[3, 1, 2] 2"
print xs[-1]     # Negative indices count from the end of the list;
xs[2] = 'foo'    # Lists can contain elements of different types
print xs         # Prints "[3, 1, 'foo']"
xs.append('bar') # Add a new element to the end of the list
print xs
x = xs.pop()     # Remove and return the lat element of the list
print x, xs

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


* Slicing: Python provides concise syntax to accesse sublists.

In [16]:
nums = range(5) # range is a built-in function that creates a list
print nums      # Prints "[0, 1, 2, 3, 4]"
print nums[2:4] # Get a slice from index 2 to 4 (exclusive);
print nums[2:]  # Get a slice from index 2 to the end;
print nums[:2]  # Get a slice from the start to index 2 (exclusive)
print nums[:]   # Get a slice of the whole list;
print nums[:-1] # Slice indices can be negative;
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print nums         # Prints "[0, 1, 8, 8, 4]

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


* Loops: You can also easily loop through elements of the list.

In [10]:
# Creates a list.
animals = ['cat', 'dog', 'monkey']
# For every element in the list.
for animal in animals:
    print animal
# Prints "cat", "dog", "monkey", each on its own line.

cat
dog
monkey


In [11]:
# Creates a list.
animals = ['cat', 'dog', 'monkey']
# The `enumerate` function gives you access to the index of the elements
# as you loop through the list.
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)
# Prints "#1: cat", "#2: dog", "#3: monkey", each on its own line

#1: cat
#2: dog
#3: monkey


* List comprehension: Allows for easily transform the data in the list into another.

In [12]:
# Let's start doing it in the long way.
# Creates a list.
nums = [0, 1, 2, 3, 4]
# Iniatilizes a list where the transformation result will be stored.
squares = []
# Loop through the list.
for x in nums:
    # Append to the result list the transformation.
    squares.append(x ** 2)
print squares # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


The code above can be replaced by using a `list comprehension`:

In [13]:
# Creates a list.
nums = [0, 1, 2, 3, 4]
# Transforms the element in the list and put the result into another list.
squares = [x ** 2 for x in nums]
print squares # Prints [0, 1, 4, 9, 16]

[0, 1, 4, 9, 16]


Comprehension can also have conditionals:

In [14]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print even_squares # Prints "[0, 4, 16]"

[0, 4, 16]


#### Dictionaries
A dictionary stores (key, value) pairs.

In [15]:
d = {'cat': 'cute', 'dog': 'furry'} # Creates a new dictionary
print d['cat']                      # Get an entry from a dictionary; prints "cute"
print 'cat' in d                    # Check if a dictionary has a given key; prints True
d['fish'] = 'wet'                   # Set an entry in a dictionary
print d['fish']                     # Prints "wet"
# print d['monkey']                 # KeyError: 'monkey' not a key of dictionary
print d.get('monkey', 'N/A')        # Get an element with a default
print d.get('fish', 'N/A')          # Get an element with a default
del d['fish']                       # Remove an element from the dictionary
print d.get('fish', 'N/A')          # "fish" is no longer a key

cute
True
wet
N/A
wet
N/A


* Loops: You can easily iterate over the keys in the dictionary.

In [16]:
# Creates a dictionary.
d = {'person': 2, 'cat': 4, 'spider': 8}
# Loop over the keys
for animal in d:
    legs = d[animal]
    print 'A %s has %d legs' % (animal, legs)
# Prints "A person has 2 legs", "A spider has 8 legs", "A cat has 4 legs" on each line

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


In [17]:
# Creates a dictionary.
d = {'person': 2, 'cat': 4, 'spider': 8} 
# The iteritems function gives you access to both keys and values for iterating over.
for animal, legs in d.iteritems():
    print 'A %s has %d legs' % (animal, legs)
# Prints "A person has 2 legs", "A spider has 8 legs", "A cat has 4 legs".

A person has 2 legs
A spider has 8 legs
A cat has 4 legs


* Dictionary comprehensions: Similiar to the list comprehension, but for creating dictonaries.

In [18]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print even_num_to_square # Prints" {0: 0, 2: 4, 4: 16}"

{0: 0, 2: 4, 4: 16}


#### Sets
A set is an unordered collection of distinct elements.

In [19]:
animals = {'cat', 'dog'} # Creates a set.
print'cat'in animals  # Check if a nelement is in a set; prints "True"
print'fish'in animals # Prints False
animals.add('fish')   # Adds element to a set
print'fish'in animals # Prints True
print len(animals)    # Number of elements in a set
animals.add('cat')    # Add an element that is already in the set
print len(animals)    # Prints 3 again
animals.remove('cat') # Remove an element from the set
print len(animals)

True
False
True
3
3
2


* Loops: Set are unordered, so we can't make assumptions about the order in which we visit the elements in the set.

In [20]:
# Creates a set.
animals = {'cat', 'dog', 'fish'}
# Loop over the elements of the set.
for idx, animal in enumerate(animals):
    print '#%d: %s' % (idx + 1, animal)
# Prints "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: dog
#3: cat


* Set comprehension: Like lists and dictionaries, we can easily construct sets using set

In [21]:
# Import the `sqrt` function from the `math` library
from math import sqrt
# Creates a set with set comprehension.
nums = {int(sqrt(x)) for x in range(30)} 
print nums # Prints "set([0, 1, 2, 3, 4, 5])"

set([0, 1, 2, 3, 4, 5])


#### Tuples
A tuple is an immutable ordered list of values. A tuple is in many ways similar to a list; one of the most important differences is that tuples can be used as keys in dictionaries and as elements of sets, while lists cannot.

In [43]:
d = {(x, x + 1): x for x in range(10)} # Create a dictionary
t = (5, 6)      # Create a tuple
print type(t)   # Prints <type 'tuple'>
print d[t]      # Prints 5
print d[(1, 2)] # Prints 1

<type 'tuple'>
5
1


### Functions
Python functions are defined using the `def` keyword:

In [23]:
# Creates a function called `sign`.
def sign(x):
    r"""Returns the sign of the given number.
    
    Given the number `x`, returns 'positive' if `x` > 0,
    returns 'negative' if `x` < 0 or returns 'zero' if `x` == 0.
    
    Parameters
    ----------
    x : numeric
        The number which the sign should be analysed.
        
    Returns
    sign : string
        String containing the result of the sign analyses: 'positive', 'negative' or 'zero'.
    """
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    # Calls the created function.
    print sign(x)
# Prints "negative, "zero" and "positive"

negative
zero
positive


Function can be defines to take optional keyword arguments:

In [24]:
# Define a funciton with the second argument as optional
def hello(name, loud=False):
    if loud:
        print 'HELLO, %s!' % name.upper()
    else:
        print 'Hello, %s' % name

hello('Bob')
hello('Fred', loud=True)            

Hello, Bob
HELLO, FRED!


### Classes
The syntax is very straightforward:

In [25]:
# Define a class called `Greeter`
class Greeter:
    
    # Constructor
    def __init__(self, name):
        self.name = name # Create an instance variable
        
    # Instance method
    def greet(self, loud=False):
        r"""Print the greeting for name in the class.

        Prints out the greeting the this instance class name,
        optionally being a loud greeting.

        Parameters
        ----------
        loud : boolean, optional
            Whether the greeting should be loud.
        """
        if loud:
            print 'HELLO, %s!' % self.name.upper() 
        else:
            print 'Hello, %s' % self.name
            
g = Greeter('Fred') # Construct an instance of the Greeter class
g.greet()           # Call an instance method; prints "Hello, Fred" 
g.greet(loud=True)  # Callaninstancemethod; prints"HELLO,FRED

Hello, Fred
HELLO, FRED!


## NumPy
NumPy is the core library for scientific computing in Python. It provides a high performance multidimensional array object, and tools for working with these arrays.

### Arrays
A NumPy array is a grid of values, all of the same type, and it is indexed by a tuple of non-negative integers. The number of dimensions is the `rank` of the array, the `shape` of an array is a tuple of integers giving the size of the array along each dimension.

In [26]:
# Import the library `numpy` as an alias of `np` for shorter.
import numpy as np

a = np.array([1,2,3])  # Create a rank 1 array
print type(a)          # Prints "<type 'numpy.ndarray'>"
print a.shape          # Prints "(3,)"
print a[0], a[1], a[2] # Prints "1 2 3"
a[0] = 5               # Change an element of the array 
print a                # Prints "[5, 2, 3]"
   
b = np.array([[1, 2, 3], [4, 5, 6]]) # Create a rank 2 array
print b.shape                        # Prints the shape of the array "(2, 3)"
print b[0, 0], b[0, 1], b[1, 0]      # Prints "1 2 4"

<type 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


We can create arrays in several ways:

In [27]:
a = np.zeros((2, 2))  # Create an array of all zeros
print a               # Prints "[[ 0. 0.]
                      #          [ 0. 0.]]"
b = np.ones((1, 2))   # Create an array of all ones
print b               # Prints "[[ 1. 1.]]"

c = np.full((2, 2), 7) # Create a constant array
print c                # Prints "[[7. 7.] 
                       #          [7. 7.]]"
d = np.eye(2)          # Create a 2x2 identity matrix
print d                # Prints "[[1. 0.]
                       #          [ 0. 1.]]"

e = np.random.random((2, 2)) # Create an array filled with random values
print e 

[[ 0.  0.]
 [ 0.  0.]]
[[ 1.  1.]]
[[ 7.  7.]
 [ 7.  7.]]
[[ 1.  0.]
 [ 0.  1.]]
[[ 0.02744397  0.84258313]
 [ 0.95471552  0.72380214]]


### Array indexing
NumPy provides several ways to index arrays:
* Slicing: similiar to Python lists. Since arrays may be multidimensionals, yoou must specify a slice for each dimension of the array.

In [31]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[1  2  3  4]
#  [4  5  6  8]
#  [9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Use slicing to pull out the subarray conssiting of the first 2 rows and columns 1 and 2.
# b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)
print

# A slice pf an array is a view into the same data,
# so modifying it will modify the original data.
print a[0, 1]  # Prints "2"
b[0, 0] = 77   # b[0, 0] is the same piece of data as a[0, 1]
print a[0, 1]

[[2 3]
 [6 7]]

2
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower ran than the original array.

In [34]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[1  2  3  4]
#  [4  5  6  8]
#  [9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank.
# while using only slices yields an array of the same rank as the original array.
row_r1 = a[1, :]   # Rank 1 view of the second row.
row_r2 = a[1:2, :] # Rank 2 view of the second row.
print row_r1, row_r1.shape  # Prints "[5 6 7 8] (4,)"
print row_r2, row_r2.shape  # Prints "[[5 6 7 8]] (1, 4)"
print

# The same distinction is valid when accessing columns of an aaray.
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print col_r1, col_r1.shape
print col_r2, col_r2.shape

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


* Integer array indexing: When you index into numpy arrays using slicing, the resulti g array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array.

In [38]:
import numpy as np

# Create an array.
a = np.array([[1, 2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The return array will have shape (3,)
print a[[0, 1, 2], [0, 1, 0]]

# The aboce example of integer array indexg is equivalent to this:
print np.array([a[0, 0], a[1, 1], a[2, 0]])

[1 4 5]
[1 4 5]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [45]:
import numpy as np

# Create a new array from which we will select elements.
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print a
print

# Create an array of indices.
b = np.array([0, 2, 0, 1])

# Select one element from each row of `a` using the indices of `b`.
print a[np.arange(4), b] # Prints "[1, 6, 7, 11]"
print

# Mutate one element from each row of `a` using the indices in `b`.
a[np.arange(4), b] += 10
print a

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[ 1  6  7 11]

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


* Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select elements of an array that satisfy some condition.

In [49]:
import numpy as np

# Create an array
a = np.array([[1, 2], [3, 4], [5, 6]])
print a
print

# Finds the elements of `a` that are bigger than 2.
# This returns a numpy array of Boolean of the
# same shape as `a`, where each slot of `bool_idx`
# tells whether that element of `a` is > 2.
bool_idx = (a > 2)
print bool_idx
print

# Now we use boolean array indexing to construct a rank 1 array
# consisting of the elements of `a` corresponding to the True values
# of `bool_idx`.
print a[bool_idx]

[[1 2]
 [3 4]
 [5 6]]

[[False False]
 [ True  True]
 [ True  True]]

[3 4 5 6]


### Datatypes
Every `NumPy` array is a grid of elements of the same type. `NumPy` provides a large set of numeric datatypes that you can use to construct arrays. `NumPy` tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument o explicitly specify the data type.

In [51]:
import numpy as np

x = np.array([1, 2])  # Lets NumPy choose the datatype
print x.dtype         # Pritns "int64"

y = np.array([1.0, 2.0])   # Lets NumPy choose the datatype
print y.dtype                          # Pritns "float64"

z = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print z.dtype

int64
float64
int64


### Array Math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overload and as function in the `NumPt` module.

In [55]:
import numpy as np

x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
# Elementwise sum
print x + y
print np.add(x, y)
print

# Elementwise difference
print x - y
print np.subtract(x, y)
print

# Elementwise product
print x * y
print np.multiply(x, y)
print

# Elementwise division
print x / y
print np.divide(x, y)
print

# Elementwise square root
print np.sqrt(x)





[[  6.   8.]
 [ 10.  12.]]
[[  6.   8.]
 [ 10.  12.]]

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]

[[  5.  12.]
 [ 21.  32.]]
[[  5.  12.]
 [ 21.  32.]]

[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]

[[ 1.          1.41421356]
 [ 1.73205081  2.        ]]


Note that the `*` operator is elementwise multiplication, not matrix multiplication. We instead use the `dot` function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. `dot` is available both as a function in the `NumPy` module and as an instance of array objects:

In [57]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# Inner product of vectors
print v.dot(w)
print np.dot(v, w)
print

# Matrix/vector product
print x.dot(v)
print np.dot(x, v)
print

# Matrix/matrix product
print x.dot(y)
print np.dot(x, y)

219
219

[29 67]
[29 67]

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


`NumPy` provides manu useful functions for performing computations on arrays. Following only the `sum` and `mean` example. Find more in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

In [60]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print np.sum(x)         # Compute the sum of all elements
print np.sum(x, axis=0) # Compute the sum of each column
print np.sum(x, axis=1) # Compute the sum of each row
print
print np.mean(x)         # Compute the mean over all elements
print np.mean(x, axis=0) # Compute the mean over the columns
print np.mean(x, axis=1) # Compute the mean over the rows

10
[4 6]
[3 7]

2.5
[ 2.  3.]
[ 1.5  3.5]


We frequently need to reshape or otherwise manipulate data in arrays. The simples example of this type of operation is transposing a matrix, as the following example. For array manipulation routines can be seen in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.array-manipulation.html).

In [70]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
print x
print
print x.T

# Note: taking the transpose of a rank 1 array does nothing.
v = np.array([1, 2, 3])
print v
print
print v.T
print 

# You can reshape the array, but should keep the right number of elements.
r = x.reshape([1, 4])
print r
print

# Can stack arrays horizontally or vertically (it takes a tuple as parameter)
print np.hstack((r, r))
print
print np.vstack((r, r))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]
[1 2 3]

[1 2 3]

[[1 2 3 4]]

[[1 2 3 4 1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]


### Broadcasting
Broadcasting is a powerful mechanism that allows `NumPy` to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each tow of a matrix. One way of doing it is:

In [72]:
import numpy as np

# We will add the vector `v` to each row of the matrix `x`,
# storing the result in the matrix `y`.
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  # Create an empty matrix with the same shape as `x``

# Add the vector `v` to each tow of the matrix `x` with an explicit loop:
for i in range(x.shape[0]):
    y[i, :] = x[i, :] + v

print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


This works fine, but when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v`vertically, then performing elementwise summation of `x` and `vv`. We couçd implement this approach like this:

In [73]:
import numpy as np

# We will add the vector `v` to each row of the matrix `x`,
# storing the result in the matrix `y`.
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# We stack 3 copies of `v` on top of each other
vv = np.tile(v, (4, 1))

# Add `x` and `vv` elementwise
y = x + vv
print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


`NumPy` broadcasting allows us to perform this computation without actually creating multiple copies of `v`:

In [74]:
import numpy as np

# We will add the vector `v` to each row of the matrix `x`,
# storing the result in the matrix `y`.
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])

# Add `v` to each row of `x` using broadcasting
y = x + v
print y

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Broadcasting two array together follows these rules:
    1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the sample length.
    2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in the dimension.
    3. The arrays ca be broadcast together if they are compatible in all dimensions.
    4. After broadcasting, each array beahves as if it has shape equal to the elementwise maximum of shapes of the two input arrays.
    5. In any dimension where one array has size 1 and the other array has size greater than 1, the first array behaves as if it were copied along that dimension.

## SciPy
`NumPy` provides a high-performance multidimensional array and basic tools to compute with and manipulate these arrays. `SciPy` builds on this, and provides a large number of functions that operate on `NumPy` arrays and are useful for different types of scientific and engineering applications. The [full documentation is here](http://docs.scipy.org/doc/scipy/reference/index.html).

### Image Operations
`SciPy` provides some basic functions to work with images. For example, it has functions to read images from disk into `NumPy` arrays, to write arrays to disk images, and to resize images.

In [7]:
from scipy.misc import imread, imsave, imresize

# Read an JPEG image into a NumPy array
img = imread('assets/cat.jpg')
print img.dtype, img.shape

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3)
# we multiply it by the array [1, 0.95, 0.9] of shape (3,)
# NumPy broadcasting means that this leaves the red channel unchanged
# and multiply the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 x 300 pixels.
img_tinted = imresize(img_tinted, (300, 300))

# Write the tinted image back to disk.
imsave('assets/cat_tinted.jpg', img_tinted)

uint8 (475, 632, 3)
